language: node_js
node_js: stable
language: node_js
node_js: 
  - "10"

branches:
  only:
    - master

git:
  quite: true
  depth: 1
  submodules: false

cache: yarn

install: yarn

script: yarn build

env:
 global:
   - GH_REF: github.com/454575238/template.git
   
deploy: 
  provider: pages
  keep-history: true
  skip-cleanup: true
  github-token: $GH_TOKEN
  local-dir: ./dist/
  on:
    branch: master
